apiVersion: v1
kind: Secret
metadata:
  namespace: app
  name: laravel-in-kubernetes
type: Opaque
stringData:
  APP_KEY: "{{{{laravelAppKey}}}}"

  DB_USERNAME: ""
  DB_PASSWORD: ""

  REDIS_PASSWORD: ""

  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""

  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"

  SLACK_API_TOKEN: ""
  FLARE_KEY: "{{{{flareKey}}}}"
