# ----------------------------------------

FROM henrotaym/composer:0.0.1 as cli

COPY composer.json composer.lock ./

RUN composer install --no-dev --no-scripts --no-autoloader --prefer-dist

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN composer install --no-dev --prefer-dist

# ----------------------------------------

FROM henrotaym/fpm:0.0.1 as fpm

COPY --from=cli --chown=www-data /opt/apps/laravel-in-kubernetes /opt/apps/laravel-in-kubernetes

# ----------------------------------------

FROM henrotaym/web:0.0.1 as web

COPY --from=cli /opt/apps/laravel-in-kubernetes/public /opt/apps/laravel-in-kubernetes/public

# ----------------------------------------

FROM cli as cron

WORKDIR /opt/apps/laravel-in-kubernetes

RUN touch laravel.cron \
    && echo "* * * * * cd /opt/apps/laravel-in-kubernetes && php artisan schedule:run" >> laravel.cron \
    && crontab laravel.cron

CMD ["crond", "-l", "2", "-f"]

# ----------------------------------------

FROM cli

# ----------------------------------------